version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: peekpick-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ppdbuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: peek_pick_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: peekpick-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /home/ec2-user/upload:/usr/share/nginx/html  # EC2의 고정 디렉토리 공유
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata: