version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: peekpick-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ppdbuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: peek_pick_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peekpick-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: peekpick-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./upload:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  pgdata: