#application-wsl.yml
spring:
  datasource:
    url: jdbc:postgresql://172.22.186.219:5432/postgres
    username: postgres
    password: ${WSL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      options:
        retry:
          max-attempts: 3         # 오류시 최대 3회 재시도
          backoff:
            delay: 5000           # 5초 간격으로 재시도
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: tbl_vector_store
        top-k: 5