spring:
#  profiles:
#    active: wsl # WSL PostgreSQL로 연결할 때만 활성화

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/peek_pick_db
    driver-class-name: org.postgresql.Driver
    username: ppdbuser
    password: ${DB_PASSWORD}

  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  mvc:
    static-path-pattern: /uploads/**

  jackson:
    property-naming-strategy: SNAKE_CASE

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      options:
        retry:
          max-attempts: 3         # 오류시 최대 3회 재시도
          backoff:
            delay: 5000           # 5초 간격으로 재시도
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: tbl_vector_store
        top-k: 5
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: OR-p_nAbry*5_9ZYp+D+

logging:
  level:
    org.beep: INFO
    org.springframework.security: TRACE


nginx:
  root-dir: "C:/nginx-1.26.3/html"

org:
  beep:
    upload: upload

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}

ors:
  api:
    key: ${ORS_API_KEY}

openai:
  summarizer:
    api-key: ${OPENAI_SUMMARIZER_KEY}