spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/peek_pick_db
    driver-class-name: org.postgresql.Driver
    username: ppdbuser
    password: ppdbuser

  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  mvc:
    static-path-pattern: /uploads/**

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.beep: INFO
    org.springframework.security: TRACE

# 사진 경로들
notice:
  image:
    upload-dir: C:/peek-pick/uploads/notices/
    base-url: http://localhost:8080/uploads/
points:
  image:
    upload-dir: C:/peek-pick-backend/upload/
inquiries:
  image:
    upload-dir: C:/peek-pick/uploads/inquiries/
    base-url: http://localhost:8080/uploads/

org:
  beep:
    upload: upload

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
